name: Deploy Landing Page to GitHub Pages & ghcr.io

on:
  push:
      branches: [ "main" ]

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  pages: write
  id-token: write
  packages: write # для пуша Docker-образа в ghcr.io

concurrency:
  group: "ci-cd-pipeline"
  cancel-in-progress: true

jobs:
  # Деплой на GitHub Pages
  deploy-2-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 'latest'
          cache: 'npm'
          cache-dependency-path: './app/package-lock.json'

      - name: Install deps
        run: npm ci

      - name: Build proj
        run: npm run build

      - name: Upload 2 Artifact GH Pages
        uses: actions/upload-pages-artifact@v5
        with:
          path: './app/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  
  # Сборка и пуш docker-образа на docker-hub и ghcr
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set lowercase variables
        run: |
          echo "IMAGE_NAME_LC=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "REPO_ONLY_LC=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # action для авторизации в ghcr
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # action для авторизации в docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_ONLY_LC }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_ONLY_LC }}:v1
            ghcr.io/${{ env.IMAGE_NAME_LC }}:latest
            ghcr.io/${{ env.IMAGE_NAME_LC }}:v1